#!/bin/sh
#
# Writes AppSecret.local.xcconfig from the environment, so a machine or CI job can
# supply the Woosmap key without touching tracked files. AppSecret.xcconfig includes
# the generated file last, so this value wins over the committed default.
#
# Usage:  WOOSMAP_PRIVATE_KEY=xxxxxxxx ./scripts/make-app-secret.sh
#
set -eu

: "${WOOSMAP_PRIVATE_KEY:?set WOOSMAP_PRIVATE_KEY to your Woosmap private API key}"

out="$(dirname "$0")/../AppSecret.local.xcconfig"
cat > "$out" <<CONFIG
// Generated by scripts/make-app-secret.sh — do not commit, do not edit by hand.
DEFAULT_PRIVATE_KEY = ${WOOSMAP_PRIVATE_KEY}
CONFIG
echo "wrote $(cd "$(dirname "$out")" && pwd)/$(basename "$out")"
